---
# tasks file for ansible-role-tripleo-baremetal-undercloud

# Do machine provisioning
- include: machine-provisioning.yml
  tags:
    - machine-provision

# Prepare machine to be used with TripleO
- include: machine-setup.yml
  tags:
    - machine-setup

# Configure repos and packages
- include: undercloud-repos-conf.yml
  delegate_to: "{{ virthost }}"
  tags:
    - undercloud-repos-conf

# Get overcloud images
- include: overcloud-images.yml
  delegate_to: "{{ virthost }}"
  tags:
    - overcloud-images
