---
- when: disk_root_device_size
  block:

    - name: get nodes UUID
      shell: |
        . {{ working_dir }}/stackrc
        ironic node-list | grep 'power' |  awk '{print $2}'
      register: ironic_node_list_uuid

    - name: find disk size from instackenv.json
      shell: |
        cat instackenv.json | grep '"disk": ' |  awk '{print $2}' | sed s/\"//g | sed s/\,//
      register: disk_size

    - name: update nodes with disk size hint
      shell: |
        . {{ working_dir }}/stackrc
        if  [ {{ disk_root_device_size | int }} -ge {{ item.1 | int }}  ]; then
          ironic node-update {{ item.0 }} add properties/root_device='{"size": {{ disk_root_device_size | int }}}'
        fi
      with_together:
        - "{{ ironic_node_list_uuid.stdout_lines }}"
        - "{{ disk_size.stdout_lines }}"

    - name: rerun introspection
      shell: |
        . {{ working_dir }}/stackrc
        openstack baremetal introspection bulk start

