---
# tasks file for ansible-role-tripleo-ssl
- name: Ensure rpm requirements for ssl are installed
  yum: name={{ item }} state=latest
  with_items:
    - openssl
  when: ssl_overcloud or ssl_undercloud

- name: Ensure tripleo heat template rpm requirements for ssl are installed
  yum: name={{ item }} state=latest
  with_items:
    - openstack-tripleo-heat-templates
  when: ssl_overcloud

- name: create self-signed SSL cert
  command: openssl req -x509 -nodes -newkey rsa:2048 -subj "/CN={{ hw_env.ExternalVIP }}" -days 3650 -keyout overcloud-privkey.pem -out overcloud-cacert.pem -extensions v3_ca
  when: ssl_overcloud

- name: fetch template from single remote host
  tls_tht:
      source_dir: "/usr/share/openstack-tripleo-heat-templates/"
      dest_dir: "{{ working_dir }}/"
      cert_filename: "overcloud-cacert.pem"
      cert_ca_filename: "overcloud-cacert.pem"
      key_filename: "overcloud-privkey.pem"
  when: ssl_overcloud

- name: copy the self-signed SSL cert
  shell: >
      cp overcloud-cacert.pem /etc/pki/ca-trust/source/anchors/;
      update-ca-trust extract;
  sudo: true
  when: ssl_overcloud
