- name: Prepare the network-isolation required networks on the undercloud
  shell: |
    {{ working_dir }}/overcloud-prep-network.sh > \
    {{ overcloud_prep_network_log }} 2>&1

- name: Add PublicVirtualFixedIPs Argument to network environment file
  set_fact:
    network_environment_args: >-
      {{ network_environment_args | combine(public_virtual_fixed_ips) }}
  when: ssl_overcloud

- name: Create network environment file for network isolation
  tags:
    - undercloud-scripts
  template:
    src: "{{ network_environment_file }}"
    dest: "{{ working_dir }}/network-environment.yaml"
    mode: 0755
  when: network_isolation
