---
- name: Parse Jenkins changes
  jenkins_deps:
    host: "{{ lookup('env', 'GERRIT_HOST') }}"
    change_id: "{{ lookup('env', 'GERRIT_CHANGE_ID') }}"
    branch: "{{ lookup('env', 'GERRIT_BRANCH') }}"
    patchset_rev: "{{ lookup('env', 'GERRIT_PATCHSET_REVISION') }}"
  when: artg_change_list is not defined and "{{ lookup('env', 'GERRIT_HOST') }}" != ""

- name: Clone and inject the specific changes
  include: roles-clone.yml artg_change={{ item }}
  with_items: artg_change_list
  when: item.project not in artg_skipped_projects
