---
- name: Get the project name
  set_fact:
    gated_project_name: '{{ gated_change.project | regex_replace("^.*/", "") }}'

- name: Check out the gated change
  git:
    repo: 'https://{{ gated_change.host }}/{{ gated_change.project }}'
    dest: '{{ lookup("env", "WORKSPACE") }}/{{ gated_project_name }}'
    refspec: '{{ gated_change.refspec }}'
    version: 'FETCH_HEAD'

- when: gated_project_name != "tripleo-quickstart"
  block:
    - name: Modify requirements
      replace:
        dest: '{{ lookup("env", "WORKSPACE") }}/tripleo-quickstart/quickstart-extras-requirements.txt'
        regexp: '^.*egg={{ gated_project_name }}$'
        replace: 'file://{{ lookup("env", "WORKSPACE") }}/{{ gated_project_name }}/#egg={{ gated_project_name }}'
    - name: Make sure the package is not installed in our venv
      pip:
        name: '{{ gated_project_name }}'
        state: absent
