---
- name: Rebuild the inventory
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-inventory

- name: Collect logs and debug data
  hosts: all:!localhost:!virthost
  gather_facts: no
  roles:
    - tripleo-collect-logs
