---
- name: Create the OVB stack
  hosts: localhost
  roles:
    - { role: ovb-manage-stack, ovb_manage_stack_mode: 'create' }

- name: Setup the undercloud
  hosts: undercloud
  gather_facts: no
  vars:
    ansible_user: root
  roles:
    - undercloud-setup

- name:  Inventory the undercloud instance
  hosts: localhost
  gather_facts: yes
  roles:
    - tripleo-inventory

- name: Fetch the overcloud images
  hosts: undercloud
  gather_facts: no
  vars:
      ansible_user: root
  roles:
   - fetch-images
