---

################
# Deploy Nodes #
################

# This is the playbook used by the `quickstart.sh` script.

# The [provision.yml](provision.yml.html) playbook is responsible for
# creating an inventory entry for our `virthost` and for creating an
# unprivileged user on that host for use by our virtual environment.
- include: provision.yml
  tags:
    - provision

# The `environment/setup` role performs any tasks that require `root`
# access on the target host.
- name: Install libvirt packages and configure networks
  hosts: virthost
  tags:
    - environment
  roles:
    - environment/setup

# The `libvirt/setup` role creates the undercloud and overcloud
# virtual machines.
- name:  Setup undercloud and overcloud vms
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/teardown
    - libvirt/setup

# Add the undercloud node to the generated
# inventory.
- name: Rebuild inventory
  hosts: localhost
  vars:
    inventory: undercloud
  roles:
    - tripleo-inventory

# DEPLOY ALL THE THINGS!  Depending on the currently selected set of
# tags, this will deploy the undercloud, deploy the overcloud, and
# perform some validation tests on the overcloud.
- name:  Install undercloud and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud
    - tripleo/overcloud

# Add the overcloud node to the generated
# inventory.
- name: Rebuild inventory
  hosts: undercloud
  gather_facts: yes
  vars:
    inventory: all
  roles:
    - tripleo-inventory

###############
# Scale Nodes #
###############

# Scale nodes w/o delete
- name: Scale overcloud nodes
  hosts: undercloud
  roles:
    - { role: tripleo-overcloud-scale, artosn_scale_nodes: true, artosn_delete_original_node: false }

# Delete the original node of type that was scaled - ensure overcloud validates after reducing scale
- name: Delete original node of type scaled
  hosts: undercloud
  roles:
    - { role: tripleo-overcloud-scale, artosn_scale_nodes: false, artosn_delete_original_node: true }

# NOTE(hrybacki: inventory regeneration and overcloud validation must be completed in a second playbook. The
# deleted node is removed from the hosts file. However, it still exists in memory and will cause the
# 'ansible-role-tripleo-inventory: regenerate ssh config' task to fail when attempting to acces non-existant host vars
