---
# defaults file for ansible-role-tripleo-ssl
working_dir: /home/stack
ssl_overcloud: false

overcloud_public_vip: 10.0.0.5
overcloud_ssl_cert_log: "{{working_dir}}/overcloud_create_ssl_cert.log"
overcloud_ssl_cert_script: overcloud-create-ssl-cert.sh.j2
